name: CI-CD

on:
  push:
    branches: [ main ]

permissions:
  contents: write   # 🔥

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Test Environment
      run: | 
        echo "Testing CI/CD pipeline for Kubernetes deployments"
        echo ${{ secrets.DOCKER_PASS }} 

    - name: Checkout
      uses: actions/checkout@v3

    - name: Login DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Build & Push Image
      run: |
        echo ${{ secrets.DOCKER_PASS }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
        # echo Erica@030720 | docker login -u Erica37 --password-stdin
        echo "Start Building Docker Image"
        docker build -t erica37/cicd-k8s:${{ github.sha }} .
        echo "Start Pushing Docker Image"
        docker push erica37/cicd-k8s:${{ github.sha }}

    - name: Update manifest
      run: |
        sed -i "s|image: .*|image: erica37/cicd-k8s:${{ github.sha }}|g" k8s/deployment.yaml

    - name: Set short SHA
      run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

    - name: Commit & Push
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add .
        git commit -m "update image to ${{ SHORT_SHA}}"
        git push